Clear-Host

#CREO UNA VARIABLE VACIA
$array5 = @()

#BUCLE DO/UNTIL QUE ACABA CUANDO EL CONTENIDO EN LA VARIABLE $NOMBRES ES IGUAL A FIN
do{

#NOMBRES QUE SE VAN A IR GUARDANDO EN EL ARRAY CREADO ARRIBA
$nombres = read-host "Escribe un nombre" 

#CONDICION QUE ESTABLECE QUE SI $NOMBRES NO ES IGUAL A FIN, 
#ESTE NO GUARDARA FIN EN $NOMBRES POR LO QUE NO ENTRARA EN EL ARRAY
if ($nombres -ne "FIN") {
    $array5 = $array5 + $nombres
}
}
until ($nombres -eq "FIN")

#CAMBIAR EL SENTIDO DE LOS ELEMENTOS DEL ARRAY
[array]::Reverse($array5)

#MUESTRO EL ARRAY INVERTIDO
Write-Host $array5